{% set name = "nr.date" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nr_date-{{ version }}.tar.gz"
  sha256: "0643aea13bcdc2a8bc56af9d5e6a89ef244c9744a1ef00cdc735902ba7f7d2e6"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - python-dateutil

test:
  imports:
    - nr

about:
  home: "https://github.com/NiklasRosenstein/python-nr.date"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Fast date parsing with timezone offset support."

extra:
  recipe-maintainers:
    - NiklasRosenstein
